name: vf_girls
description: 使用 Flutter 实现一个加载妹子图项目

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# 发布时需要的依赖库
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 图标库
  cupertino_icons: ^0.1.2
  # 国际化
  flutter_i18n: ^0.8.2         
  flutter_screenutil: ^0.7.0

  # 网络请求
  dio: ^3.0.6
  # JSON 解析
  json_annotation: ^3.0.0
  # 加载网页
  webview_flutter: ^0.3.16
  # html 数据解析
  html: 0.14.0+3

  # 路径
  path_provider: ^1.4.5
  # 本地存储
  localstorage: ^3.0.1+4
  # SharedPreferences
  shared_preferences: ^0.5.4+6
  # Toast
  oktoast: ^2.2.0
  # 轮播 Banner
  flutter_swiper: ^1.1.6
  # 瀑布流布局
  flutter_staggered_grid_view: ^0.3.0
  # 下拉刷新
  flutter_easyrefresh: ^2.0.8

  # 状态管理
  provider: ^3.1.0+1

  # 获取设备信息
  device_info: ^0.4.0+4
  package_info: ^0.4.0+12

  ### 源码依赖，可以引用 git 上的源码以及本地源码
  # vf_plugin:
  #   git:
  #     url: git@github.com:lzan13/vf_plugin.git
  #     ref: master
  vf_plugin:
    path: ../vf_plugin

# 开发时需要的依赖库
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.3


flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/langs/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
